### ISSUE TITLE
WorkService.loadCapacities.findTeams TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by ryancdotnet** [NielZeeman/team-capacity-extension#1]
Extension does not work. When clicking the "Team Capacity" tab on the Work page for any team, we receive this error.

Our configuration for TFS is: one TFS Project, many TFS Teams.

Here are the error details to the best I could grab:

Script location:
https://(REDACTED).visualstudio.com/(REDACTED)/(REDACTED)/_apps/hub/tfc.team-capacity.team-capacity-management-hub

Exception message: WorkService.loadCapacities.findTeams TypeError: Cannot read property 'id' of null

Stack Trace:
WorkService.loadCapacities.findTeams TypeError: Cannot read property 'id' of null @ index.js:formatted:4343
e.LogError @ index.js:formatted:4343
(anonymous) @ index.js:formatted:20736
l @ vss-bundle-ext-core-vbyMfpW8MeUMykXAfdRAK_5ibk898-gmWY-Q_SAu6Tsc=:27
(anonymous) @ vss-bundle-ext-core-vbyMfpW8MeUMykXAfdRAK_5ibk898-gmWY-Q_SAu6Tsc=:27
when @ vss-bundle-ext-core-vbyMfpW8MeUMykXAfdRAK_5ibk898-gmWY-Q_SAu6Tsc=:27
u.promiseDispatch @ vss-bundle-ext-core-vbyMfpW8MeUMykXAfdRAK_5ibk898-gmWY-Q_SAu6Tsc=:27
(anonymous) @ vss-bundle-ext-core-vbyMfpW8MeUMykXAfdRAK_5ibk898-gmWY-Q_SAu6Tsc=:27
t @ vss-bundle-ext-core-vbyMfpW8MeUMykXAfdRAK_5ibk898-gmWY-Q_SAu6Tsc=:27

**Comment by eduardoguilarducci** [comment]
Hi @ryancdotnet, 

It happens when one (or more) of your teams has no Iterations defined. If all your teams has iterations and capacity defined, will you not receive this error anymore. 

Sure this is a bug that should be fixed.

**Comment by NielZeeman** [comment]
Hi,

Thanks for your comments.
And yes, the fix is being deployed at the moment.
