### ISSUE TITLE
install not enable

### ISSUE THREAD

**Issue by fabriziomonte** [NielZeeman/team-capacity-extension#14]
Hello,
i am unable to install: can help me?
Thanks

![tcm](https://user-images.githubusercontent.com/47635663/52793499-29f57a00-306e-11e9-9c0d-4747d6177b2c.jpg)

**Comment by NielZeeman** [comment]
Hi,

I presume you are installing it on-prem?
Can you tell me if you install directly from the market place, or are you downloading the extension first ?

Thanks

**Comment by fabriziomonte** [comment]
Hi,
I’m  installing it on-prem.
I have downloading the extension first.
Thanks



Da: Niel Zeeman <notifications@github.com>
Inviato: venerdì 15 febbraio 2019 13:23
A: NielZeeman/team-capacity-extension <team-capacity-extension@noreply.github.com>
Cc: Fabrizio Monte <Fabrizio.Monte@aurigaspa.com>; Author <author@noreply.github.com>
Oggetto: Re: [NielZeeman/team-capacity-extension] install not enable (#14)


Hi,

I presume you are installing it on-prem?
Can you tell me if you install directly from the market place, or are you downloading the extension first ?

Thanks

**Comment by NielZeeman** [comment]
Hi,
Can you confirm that you have rights to install the extension..
and then tell me the exact version of TFS you are using.
I'm also assuming you are using an Italian language ? 
This is so that I can setup a local test bed to see if I can replicate the issue.

Thanks

**Comment by fabriziomonte** [comment]
Hi,
I am an admin user. The version is TFS 2017 Update 3,  Italian language.
Thanks

Fabrizio  MONTE
phone +39.080.5692.203
mobile +39.334.8135726
Auriga SpA            - Strada Vassallo, 1        70125 Bari - IT
                               - Via don Guanella 15/B  70124 Bari - IT
                               - Via don Guanella 17     70124 Bari - IT
Phone +39.080.56.92.111 - Fax +39.080.56.92.112
www.aurigaspa.com<http://www.aurigaspa.com/> – info@aurigaspa.com<mailto:info@aurigaspa.com>

Pursuant to Legislative Decree No. 196/2003, you are hereby informed that this message contains confidential information intended only for the use of the addressee. If you are not the addressee, and have received this message by mistake, please delete it and immediately notify us. You may not copy or disseminate this message to anyone. Thank you.
**Think about the environment before printing**

[Immagine in firma_ Auriga 2018]


Da: Niel Zeeman <notifications@github.com>
Inviato: lunedì 18 febbraio 2019 09:41
A: NielZeeman/team-capacity-extension <team-capacity-extension@noreply.github.com>
Cc: Fabrizio Monte <Fabrizio.Monte@aurigaspa.com>; Author <author@noreply.github.com>
Oggetto: Re: [NielZeeman/team-capacity-extension] install not enable (#14)


Hi,
Can you confirm that you have rights to install the extension..
and then tell me the exact version of TFS you are using.
I'm also assuming you are using an Italian language ?
This is so that I can setup a local test bed to see if I can replicate the issue.

Thanks

**Comment by NielZeeman** [comment]
Thank you for your patience.
I tracked down the issue to a setting in the manifest that causes this issue.
I have updated the manifest accordingly.

**Comment by fabriziomonte** [comment]
Hi,
the installation was successful.
I thank you so much

Fabrizio  MONTE
phone +39.080.5692.203
mobile +39.334.8135726
Auriga SpA            - Strada Vassallo, 1        70125 Bari - IT
                               - Via don Guanella 15/B  70124 Bari - IT
                               - Via don Guanella 17     70124 Bari - IT
Phone +39.080.56.92.111 - Fax +39.080.56.92.112
www.aurigaspa.com<http://www.aurigaspa.com/> – info@aurigaspa.com<mailto:info@aurigaspa.com>

Pursuant to Legislative Decree No. 196/2003, you are hereby informed that this message contains confidential information intended only for the use of the addressee. If you are not the addressee, and have received this message by mistake, please delete it and immediately notify us. You may not copy or disseminate this message to anyone. Thank you.
**Think about the environment before printing**

[Immagine in firma_ Auriga 2018]


Da: Niel Zeeman <notifications@github.com>
Inviato: lunedì 18 febbraio 2019 14:37
A: NielZeeman/team-capacity-extension <team-capacity-extension@noreply.github.com>
Cc: Fabrizio Monte <Fabrizio.Monte@aurigaspa.com>; Author <author@noreply.github.com>
Oggetto: Re: [NielZeeman/team-capacity-extension] install not enable (#14)


Thank you for your patience.
I tracked down the issue to a setting in the manifest that causes this issue.
I have updated the manifest accordingly.
