### ISSUE TITLE
fails to install

### ISSUE THREAD

**Issue by GuidoLL** [NielZeeman/team-capacity-extension#16]
Tried to install but fails see below logs. Will your extension be compatible in the future?

22/05/2019 16:20:08 - Microsoft VSIX Installer
22/05/2019 16:20:08 - -------------------------------------------
22/05/2019 16:20:08 - vsixinstaller.exe version:
22/05/2019 16:20:08 - 15.9.3041
22/05/2019 16:20:08 - -------------------------------------------
22/05/2019 16:20:08 - Command line parameters:
22/05/2019 16:20:08 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\P10490881\Downloads\tfc.team-capacity-0.0.14.vsix
22/05/2019 16:20:08 - -------------------------------------------
22/05/2019 16:20:08 - Microsoft VSIX Installer
22/05/2019 16:20:08 - -------------------------------------------
22/05/2019 16:20:08 - Initializing Install...
22/05/2019 16:20:09 - Extension Details...
22/05/2019 16:20:09 - 	Identifier         : team-capacity
22/05/2019 16:20:09 - 	Name               : Team Capacity Management
22/05/2019 16:20:09 - 	Author             : tfc
22/05/2019 16:20:09 - 	Version            : 0.0.14
22/05/2019 16:20:09 - 	Description        : Provides and overview of the assigned capacity of individual team members across multiple teams within a team project
22/05/2019 16:20:09 - 	Locale             : en-US
22/05/2019 16:20:09 - 	MoreInfoURL        : 
22/05/2019 16:20:09 - 	InstalledByMSI     : False
22/05/2019 16:20:09 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
22/05/2019 16:20:09 - 
22/05/2019 16:20:09 - 	SignatureState     : Unsigned
22/05/2019 16:20:09 - 	Supported Products : 
22/05/2019 16:20:09 - 		Microsoft.VisualStudio.Services
22/05/2019 16:20:09 - 			Version : 
22/05/2019 16:20:09 - 
22/05/2019 16:20:09 - 	References         : 
22/05/2019 16:20:09 - Signature Details...
22/05/2019 16:20:09 - 	Extension is not signed.
22/05/2019 16:20:09 - 
22/05/2019 16:20:09 - Searching for applicable products...
22/05/2019 16:20:09 - Found installed product - Global Location
22/05/2019 16:20:09 - Found installed product - Visual Studio Community 2017
22/05/2019 16:20:12 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by NielZeeman** [comment]
This is not a visual studio extension. It needs to be installed using the Azure DevOps extension manager
