### ISSUE TITLE
When click on team get an error: TF400813: Resource not available for anonymous access. Client authentication required.

### ISSUE THREAD

**Issue by shayki5** [NielZeeman/team-capacity-extension#19]
Hi,
Thank you so much for your great extension!
We have an issue in our TFS 2018.3, when I go to the Team Capacity extension tab everything is fine. but when I clicked on a specific team, a new tab for the team capacity is open but I got a red window with an error:

> TF400813: Resource not available for anonymous access. Client authentication required.

![image](https://user-images.githubusercontent.com/26063853/66044948-5db4df80-e52b-11e9-8a0a-061666a09cfa.png)

I can close it and it's ok, I got the correct team capacity page.

Can you check why I got this errors?

It occurs to each user even if he collection admin.

Thank you,
Shayki

**Comment by NielZeeman** [comment]
Hi,
I can't really thing of anything off-hand. It merely opens a url in a new tab.
It could be a security setting or policy in the browser. 
What browser are you using?
And is the URL that is being opened correct in terms of the TFS url?

**Comment by shayki5** [comment]
Hi @NielZeeman,
Thank you for your response!
I checked now and it occurs in Chrome and IE, in Edge is not occurs.
We are really a secure company so it make sense there is a policies on the browser.
Do you have an idea where to check?

Best regards,
Shayki

**Comment by NielZeeman** [comment]
It seems that is a error that is fairly common one.
There are a couple of things you can look at:

- Make sure the windows credentials are all removed and then renewed for the TFS 
- Make sure the TFS is added into the browsers trusted / local site zone
- Clear the browser cache and history
- Last resort, make sure that Anonymous authentication on IIS has been disabled for the TFS site

Hope this helps

**Comment by shayki5** [comment]
Thank you!
Cache and credentials are not the issue (the error exist in a few computers).
My manager not want to touch the tfs server (:() and he decided not to install it.
Thanks for your help!
