### ISSUE TITLE
Team Capacity in Azure DevOps

### ISSUE THREAD

**Issue by bushra0107** [NielZeeman/team-capacity-extension#25]
Team Capacity is spinning in one of the projects on Azure Devops. We recently added new teams and now it is not working.. We have added iterations to all of teams but still it is just spinning. Can anyone help?

**Comment by NielZeeman** [comment]
@bushra0107 The best way to check what went wrong was to look at the web console.
I have now removed the extension due to lack of interest to update and the changes in API has caused serious functional problems.

**Comment by bushra0107** [comment]
![console](https://user-images.githubusercontent.com/123774279/215691090-273bbe93-7c90-4079-9157-f331aed9aa54.png)
