### ISSUE TITLE
The extension throwing an error "The iteration might have been deleted, or it might not be selected for your team."

### ISSUE THREAD

**Issue by sriramdasbalaji** [NielZeeman/team-capacity-extension#3]
Hi,

I have installed the Team Capacity Extension. When I click on Team Capacity tab I am getting the below error.
"WorkService.loadTeam.findTeamSettings.findCapacity TFS.WebApi.Exception: VS1530019: Cannot find iteration with id '72663474-a3af-43bc-a011-a3e136482cb5'. The iteration might have been deleted, or it might not be selected for your team."
![image](https://user-images.githubusercontent.com/13716984/33562190-a84cbd82-d93a-11e7-8921-ce554042052f.png)

The Iteration is not deleted and it is selected for the team.
Please let us know how we can fix this issue.

Thanks 
Sriramdas Balaji

**Comment by NielZeeman** [comment]
Hi @sriramdasbalaji 
Can you please advise if you do indeed have access to the given iteration, and that there are capacities setup for it?

**Comment by sriramdasbalaji** [comment]
Hi @NielZeeman,
Thanks for your response.
I am the member of Project Administrators group and I do have the permissions to all iterations.

Thanks
Sriramdas Balaji

**Comment by NielZeeman** [comment]
I have not been able to find the cause of that error. How many teams do you have?
Is it possible to provide some information?
Can you  see the response and queries using developer tools in the browser. Find the team and iteration that is causing the problem and provide some more info around them?

You will notice that the error occurs on a url that looks something like this:
https://{account}.visualstudio.com/DefaultCollection/{project}/{team}/_apis/work/TeamSettings/Iterations/{iterationid}/Capacities

**Comment by sriramdasbalaji** [comment]
Hi @NielZeeman ,

Thanks for your inputs. we are able to fix the issue. When I used Developer tools in the browser I found an exception as below
![image](https://user-images.githubusercontent.com/13716984/33760303-36b936f2-dc2b-11e7-82f2-a1475650a76c.png)
 I have set the Default iteration for the team and it worked.

Thanks
Sriramdas Balaji

**Comment by NielZeeman** [comment]
Hi @sriramdasbalaji 

Thank you for your feedback, I will put in a check for that so that the error does not occur again
