### ISSUE TITLE
Problem with scrolling

### ISSUE THREAD

**Issue by gibf** [NielZeeman/team-capacity-extension#5]
Hi
I have just installed the team-capacity-extension and can only see half of the members and have to drag the browser over two screens in order to see the all the teams.
Is it possible to get the scroll bars to work on TFS 2018? and is it possible to only see members on the team and not all members of the team project? 

regards
Gitte

**Comment by NielZeeman** [comment]
Hi
Thank you for your feedback.
The members is a list of all members that has capacity assigned in one or more teams. 
I'll see what is possible with the scroll bars.

**Comment by NielZeeman** [comment]
Hi,
Thank you for the suggestion. It is on my radar.
I have just published an update that enables scrollbars for large number of teams and members

**Comment by AmitBhatnagar24** [comment]
I have many teams, but not so many team members. I do not have a horizontal scrollbar to see all of columns which means I have to extend over 2 monitors as the OP mentioned. @NielZeeman  mentioned that an update enabled scrollbars? I don't see it?!
