### ISSUE TITLE
Team Capacity Management

### ISSUE THREAD

**Issue by AnnaZakomoldina** [NielZeeman/team-capacity-extension#8]
Good afternoon. installed the application, but it does not work for us. What do I need to do to allow users to load? Message comes out "No Capacities assigned or found"

**Comment by NielZeeman** [comment]
Hi,
Can you please 
1. check what the default iterations are set to in the team configurations?
2. provide me the console log from the browser when you load the extension?

**Comment by NielZeeman** [comment]
a discussion and probable issue in [issue 10](https://github.com/NielZeeman/team-capacity-extension/issues/10)
